### PR TITLE
Update square.class.php

### PR DESCRIPTION
**Pull request by zaazz**
Changed Square class to be just a Rectangle with the same length and width.

### CODE REVIEW

**Comment by ggorlen** [comment]
Great job!  Thoughts:
- instance data $size isn't assigned or used--can it be omitted?
- if (is_numeric($size) && $size > 0) etc should be handled in the parent class, as well as the exception.
- problem: I can make a Square, then use a length or width setter from the parent class to turn my Square into a rectangle, breaking the class logic!  Is there an elegant way to override these length and width setters from the parent to prevent this?
- area, rendering, getters, and perimeter are all done!

Do you have any other ideas for subclasses?  Totally optional, we're overkill on the assignment, so just do as much as you feel is educational.  The Triangle subclasses, Polygon and etc are quite a bit tougher, but I think this stuff is ultra-informative and involves some CS brainwork, whereas the rest of the course is mostly syntax and scripting (also important).

**Comment by zaazz** [comment]
Good points! I’ll see if I can revise the square again. 

I uploaded the polygon class to my branch at
https://github.com/zaazz/cs130a/blob/master/group-assignment-03/polygon.class.php <https://github.com/zaazz/cs130a/blob/master/group-assignment-03/polygon.class.php>

It doesn’t calculate the area or perimeter yet (still has leftovers from the circle class). We don’t really need it, as you say, but if you have time, feel free to take a look and make suggestions. I’m so new at this that my code is super clunky.

I can’t quite figure out GitHub. I can’t sync my branch up to yours. I could sync my desktop version, but not the one on the web. And then somehow I duplicated a bunch of files outside of their folders. Oh well. I’m going to take a break. 

Have a great night!
Julie Ann




On Apr 8, 2017, at 5:56 PM, Greg Gorlen <notifications@github.com> wrote:

Great job! Thoughts:

instance data $size isn't assigned or used--can it be omitted?
if (is_numeric($size) && $size > 0) etc should be handled in the parent class, as well as the exception.
problem: I can make a Square, then use a length or width setter from the parent class to turn my Square into a rectangle, breaking the class logic! Is there an elegant way to override these length and width setters from the parent to prevent this?
area, rendering, getters, and perimeter are all done!
Do you have any other ideas for subclasses? Totally optional, we're overkill on the assignment, so just do as much as you feel is educational. The Triangle subclasses, Polygon and etc are quite a bit tougher, but I think this stuff is ultra-informative and involves some CS brainwork, whereas the rest of the course is mostly syntax and scripting (also important).

**Comment by ggorlen** [comment]
Cool--nice work!  Looks like you're creating a RegularPolygon class, which is great since I wrote a generalized Polygon class that also works for irregular polygons, which I'll commit now.  Here's the thing about inheritance in programming: if you use the extends keyword, you're essentially saying "Polygon is a special kind of Circle," which we know isn't quite true, but you have the right idea.  In the case of a square, it's very much still a rectangle, just a specific kind of rectangle.  I'm thinking Polygon is a highly generalized shape, not a specific kind of circle, and should directly subclass Shape.  We can then subclass Polygon with all kinds of stuff : RegularPolygon, which is what your code appears to be, which enforces equal sides but doesn't specify how many, which can then be subclassed by Hexagons, Rhombuses, Octagons, etc etc.  Obviously, we won't have time for all this, but that's the general principle--moving from broad to specific.  As for github. don't worry too much about it, you'll get the hang of it.  I don't recommend using the Github Desktop client, though, I would go for the command line--it's way less confusing in the long run.  As mentioned, I added you as a contributor, so you can edit my original repository as if it were your own, AFAIK.  Pull or download the latest version with your client, make changes, type "git add -A" "git commit -m "add some new stuff" and "git push" -- if it doesn't work, just literally upload in the browser should work.
Best,
Greg

**Comment by ggorlen** [comment]
By the way, the interesting thing about the Polygon class is that it does a LOT of work for every subclass.  A Triangle happens to be a Polygon, so I was able to remove all of the code from the Triangle class except for the "three sides" constraint, so have a look at Triangle as it stands now--most other subclasses of Polygon or RegularPolygon should look more or less like this.

**Comment by zaazz** [comment]
Hi Greg,

I just updated the square class to accommodate the case of someone trying to use setLength or setWidth. This seemingly simple thing is not so simple! As far as I can figure — since we have those methods as public in the Rectangle class, Square automatically inherits them, and they can’t be made private. I can only change the functions. I thought of having setLength call setWidth and vice versa, but then we’d get into an endless loop. I don’t seem to be able to merge changes, so I left it as a Pull Request.

I like what you did with the Polygon & Triangle. I have to move on to Assignment 10 and the quiz, so I’m not sure I’ll get to fixing up the Regular Polygon. I see what you’re saying about the regular polygon not really being a circle. I was just trying to reuse some of the circle’s properties, like origin & radius.

Not that we have to do this, but if we had all the time in the world, would it be good to overload the shape class with all the possible functions & properties? So the general Shape could have an origin, radius, length, width, vertices, etc.  And then each inherited class could use whichever properties are relevant? Although then we run into the problem of having to override or eliminate the properties & methods that we don’t want. Hmm. Okay, on to input & output!

Thanks!
Julie Ann


On Apr 8, 2017, at 8:55 PM, Greg Gorlen <notifications@github.com> wrote:

By the way, the interesting thing about the Polygon class is that it does a LOT of work for every subclass. A Triangle happens to be a Polygon, so I was able to remove all of the code from the Triangle class except for the "three sides" constraint, so have a look at Triangle as it stands now--most other subclasses of Polygon or RegularPolygon should look more or less like this.

**Pull request merged**
